openapi: 3.0.3
info:
  title: Greeting API
  version: 1.0.0
tags:
  - name: greeting
paths:
  /greeting:
    get:
      tags:
        - greeting
      operationId: getGreeting
      summary: Returns a greeting message
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Name to include in the greeting
      responses:
        '200':
          description: A greeting object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
      required:
        - id
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
        - message
        - status
